name: "pochi GitHub Action"
description: "Run pochi AI assistant in GitHub Actions workflows"
branding:
  icon: "code"
  color: "blue"

inputs:
  model:
    description: "The AI model to use for pochi tasks"
    required: false

runs:
  using: "composite"
  steps:
    - name: Resolve target SHA for reactions
      shell: bash
      run: |
        TARGET_SHA="${{ github.sha }}"
        # For pull_request events, prefer the head SHA
        if [ "${{ github.event_name }}" = "pull_request" ] && [ -n "${{ github.event.pull_request.head.sha }}" ]; then
          TARGET_SHA="${{ github.event.pull_request.head.sha }}"
        fi
        echo "TARGET_SHA=$TARGET_SHA" >> $GITHUB_ENV

    - name: Add :eyes: reaction (job started)
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        curl -s -X POST \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${GH_REPO}/commits/${TARGET_SHA}/reactions" \
          -d '{"content":"eyes"}' || true

    - name: Install pochi CLI
      shell: bash
      run: |
        echo "Installing pochi CLI..."
        curl -fsSL https://app.getpochi.com/install.sh | bash

        echo "Installing ripgrep..."
        curl -LO 'https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz'
        tar -xzf ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
        mv ripgrep-14.1.1-x86_64-unknown-linux-musl/rg "$HOME/.pochi/bin/"
        rm -rf ripgrep-14.1.1-x86_64-unknown-linux-musl*

        echo "$HOME/.pochi/bin" >> $GITHUB_PATH

    - name: Config Git
      shell: bash
      run: |
        git config --global user.email "noreply@getpochi.com"
        git config --global user.name "Pochi"

    - name: Install bun
      shell: bash
      run: |
        curl -fsSL https://bun.com/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install --frozen-lockfile

    - name: Run pochi GitHub Action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        POCHI_REMOTE_ENV: 1
      run: |
        if [ -n "${{ inputs.model }}" ]; then
          export POCHI_MODEL="${{ inputs.model }}"
        fi
        bun ${GITHUB_ACTION_PATH}/src/index.ts

    # Success reaction
    - name: Add +1 reaction (job succeeded)
      if: success()
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        curl -s -X POST \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${GH_REPO}/commits/${TARGET_SHA}/reactions" \
          -d '{"content":"+1"}' || true

    - name: Add confused reaction (job failed)
      if: failure()
      shell: bash
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        curl -s -X POST \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${GH_REPO}/commits/${TARGET_SHA}/reactions" \
          -d '{"content":"confused"}' || true
