name: "pochi GitHub Action"
description: "Run pochi AI assistant in GitHub Actions workflows"
branding:
  icon: "code"
  color: "blue"

inputs:
  model:
    description: "The AI model to use for pochi tasks"
    required: false

runs:
  using: "composite"
  steps:
    - name: Add initial reaction and create progress comment
      shell: bash
      run: |
        # Get comment ID from GitHub context
        COMMENT_ID=$(echo '${{ github.event.comment.id }}')
        ISSUE_NUMBER=$(echo '${{ github.event.issue.number }}')
        
        # Debug output
        echo "Debug: COMMENT_ID=$COMMENT_ID"
        echo "Debug: ISSUE_NUMBER=$ISSUE_NUMBER"
        echo "Debug: REPOSITORY=${{ github.repository }}"
        
        # Add eyes reaction to indicate starting
        EYES_REACTION_RESPONSE=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/comments/$COMMENT_ID/reactions \
          -d '{"content":"eyes"}')
        
        # Debug output for eyes reaction response
        echo "Debug: EYES_REACTION_RESPONSE=$EYES_REACTION_RESPONSE"
        
        # Extract eyes reaction ID and export as environment variable
        EYES_REACTION_ID=$(echo $EYES_REACTION_RESPONSE | grep -o '"id":[0-9]*' | head -1 | cut -d':' -f2)
        echo "Debug: Extracted EYES_REACTION_ID=$EYES_REACTION_ID"
        echo "EYES_REACTION_ID=$EYES_REACTION_ID" >> $GITHUB_ENV
        
        # Create initial progress comment
        PROGRESS_COMMENT_RESPONSE=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
          -d "{\"body\":\"🔄 **Pochi Running...**\\n\\nStarting Pochi execution...\\n\\n🔗 **[View GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**\"}")
        
        # Debug output for progress comment response
        echo "Debug: PROGRESS_COMMENT_RESPONSE=$PROGRESS_COMMENT_RESPONSE"
        
        # Extract progress comment ID and export as environment variable
        PROGRESS_COMMENT_ID=$(echo $PROGRESS_COMMENT_RESPONSE | grep -o '"id":[0-9]*' | head -1 | cut -d':' -f2)
        echo "Debug: Extracted PROGRESS_COMMENT_ID=$PROGRESS_COMMENT_ID"
        echo "PROGRESS_COMMENT_ID=$PROGRESS_COMMENT_ID" >> $GITHUB_ENV

    - name: Install pochi CLI
      shell: bash
      run: |
        if ! curl -fsSL https://app.getpochi.com/install.sh | bash > /dev/null 2>&1; then
          echo "Error: Failed to install pochi CLI"
          exit 1
        fi

        if ! curl -sLO 'https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz'; then
          echo "Error: Failed to download ripgrep"
          exit 1
        fi
        if ! tar -xzf ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz > /dev/null 2>&1; then
          echo "Error: Failed to extract ripgrep"
          exit 1
        fi
        if ! mv ripgrep-14.1.1-x86_64-unknown-linux-musl/rg "$HOME/.pochi/bin/"; then
          echo "Error: Failed to move ripgrep binary"
          exit 1
        fi
        rm -rf ripgrep-14.1.1-x86_64-unknown-linux-musl*

        echo "$HOME/.pochi/bin" >> $GITHUB_PATH

    - name: Config Git
      shell: bash
      run: |
        git config --global user.email "noreply@getpochi.com"
        git config --global user.name "Pochi"

    - name: Install bun
      shell: bash
      run: |
        if ! curl -fsSL https://bun.com/install | bash > /dev/null 2>&1; then
          echo "Error: Failed to install bun"
          exit 1
        fi
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        if ! bun install --frozen-lockfile --silent; then
          echo "Error: Failed to install dependencies"
          exit 1
        fi

    - name: Run pochi GitHub Action
      shell: bash
      run: |
        if [ -n "${{ inputs.model }}" ]; then
          export POCHI_MODEL="${{ inputs.model }}"
        fi
        bun ${GITHUB_ACTION_PATH}/src/index.ts
      env:
        GITHUB_TOKEN: ${{ github.token }}
        POCHI_REMOTE_ENV: 1
        PROGRESS_COMMENT_ID: ${{ env.PROGRESS_COMMENT_ID }}
        EYES_REACTION_ID: ${{ env.EYES_REACTION_ID }}
