name: "pochi GitHub Action"
description: "Run pochi AI assistant in GitHub Actions workflows"
branding:
  icon: "code"
  color: "blue"

inputs:
  model:
    description: "The AI model to use for pochi tasks"
    required: false

runs:
  using: "composite"
  steps:
    - name: Clone Pochi repository
      shell: bash
      run: |
        git clone --depth 1 https://github.com/Sma1lboy/pochi /tmp/pochi-source

    - name: Install bun
      shell: bash
      run: |
        curl -fsSL https://bun.com/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Build Pochi CLI
      shell: bash
      run: |
        cd /tmp/pochi-source
        bun install --frozen-lockfile
        cd packages/cli
        bun run build
        chmod +x ./dist/pochi

    - name: Install ripgrep
      shell: bash
      run: |
        curl -sLO 'https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz'
        tar -xzf ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz
        mkdir -p "$HOME/.pochi/bin"
        mv ripgrep-14.1.1-x86_64-unknown-linux-musl/rg "$HOME/.pochi/bin/"
        rm -rf ripgrep-14.1.1-x86_64-unknown-linux-musl*
        echo "$HOME/.pochi/bin" >> $GITHUB_PATH

    - name: Config Git
      shell: bash
      run: |
        git config --global user.email "noreply@getpochi.com"
        git config --global user.name "Pochi"

    - name: Setup initial reaction and progress comment
      shell: bash
      run: |
        cd /tmp/pochi-source/packages/github-action
        bun install --frozen-lockfile
        bun src/preprocess-action.ts
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run Pochi GitHub Action
      shell: bash
      run: |
        cd /tmp/pochi-source/packages/github-action
        if [ -n "${{ inputs.model }}" ]; then
          export POCHI_MODEL="${{ inputs.model }}"
        fi
        export POCHI_CLI_PATH="/tmp/pochi-source/packages/cli/dist/pochi"
        bun src/index.ts
      env:
        GITHUB_TOKEN: ${{ github.token }}
        POCHI_REMOTE_ENV: 1
        PROGRESS_COMMENT_ID: ${{ env.PROGRESS_COMMENT_ID }}
        EYES_REACTION_ID: ${{ env.EYES_REACTION_ID }}
